# Default values for sriov-fec-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

operatorGroup:
  # Specifies whether a operator group should be created
  create: true
  # Overrides the service account which will be used to deploy operator(s) in this operator group.
  serviceAccountName: ""
  # Overrides the targetNamespaces whose default is the release namespace.
  targetNamespaces: ""

subscription:
  channel: stable
  source: certified-operators
  sourceNamespace: openshift-marketplace
  # Approval is the user approval policy for an InstallPlan. It must be one of "Automatic" or "Manual".
  installPlanApproval: Automatic

# Specifies whether a csv should be deleted during uninstallation.
clusterServiceVersionDeleteCascade: true
