apiVersion: sriovfec.intel.com/v2
kind: SriovFecClusterConfig
metadata:
  name: {{ include "n3000-fec-config.fullname" . }}
  labels:
    {{- include "n3000-fec-config.labels" . | nindent 4 }}
spec:
  priority: {{ .Values.priority }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  acceleratorSelector:
    {{- with .Values.acceleratorSelector }}
    pciAddress: {{ .pciAddress }}
    {{- if .deviceID -}}
    deviceIDs: {{ .deviceID }}
    {{- end }}
    {{- if .driver -}}
    driver: {{ .driver }}
    {{- end }}
    {{- if .vendorID -}}
    vendorID: {{ .vendorID }}
    {{- end }}
    {{- end }}
  physicalFunction:  
    {{- with .Values.physicalFunction }}
    pfDriver: {{ .pfDriver }}
    vfDriver: {{ .vfDriver }}
    vfAmount: {{ .vfAmount }}
    {{- end }}
    bbDevConfig:
      n3000:
        {{- with .Values.physicalFunction.bbDevConfigN3000 }}
        # Network Type: either "FPGA_5GNR" or "FPGA_LTE"
        networkType: {{ .networkType | quote }}
        # Programming mode: 0 = VF Programming, 1 = PF Programming
        pfMode: {{ .pfMode }}
        flrTimeout: {{ .flrTimeout }}
        {{- with .downlink }}
        downlink:
          bandwidth: {{ .bandwidth }}
          loadBalance:  {{ .loadBalance }}
          {{- with .queues }}
          queues:
            vf0: {{ .vf0 }}
            vf1: {{ .vf1 }}
            vf2: {{ .vf2 }}
            vf3: {{ .vf3 }}
            vf4: {{ .vf4 }}
            vf5: {{ .vf5 }}
            vf6: {{ .vf6 }}
            vf7: {{ .vf7 }}
          {{- end }}
        {{- end }}
        {{- with .uplink }}
        uplink:
          bandwidth: {{ .bandwidth }}
          loadBalance: {{ .loadBalance }}
          {{- with .queues }}
          queues:
            vf0: {{ .vf0 }}
            vf1: {{ .vf1 }}
            vf2: {{ .vf2 }}
            vf3: {{ .vf3 }}
            vf4: {{ .vf4 }}
            vf5: {{ .vf5 }}
            vf6: {{ .vf6 }}
            vf7: {{ .vf7 }}
          {{- end }}
        {{- end }}
        {{- end }}
