{{- if .Values.operatorGroup.create -}}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "sriov-fec-operator.fullname" . }}
  labels:
    {{- include "sriov-fec-operator.labels" . | nindent 4 }}
spec:
  {{- $relns := .Release.Namespace -}}
  {{- with .Values.operatorGroup }}
  {{- if .serviceAccountName -}}
  serviceAccountName: {{ .serviceAccountName | quote }}
  {{- end }}
  targetNamespaces:
    - {{ .targetNamespaces | default $relns | quote  }}
  {{- end }}
{{- end }}
