{{- if .Values.clusterServiceVersionDeleteCascade -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "sriov-fec-operator.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
        image: registry.redhat.io/openshift4/ose-cli:v4.9.0-202201261125.p0.g3f16530.assembly.stream
        command:
        - /bin/bash
        - -c
        - 'oc delete csv $(oc get subscription {{ include "sriov-fec-operator.fullname" . }} -o jsonpath="{.status.currentCSV}")'
      restartPolicy: Never
      serviceAccountName: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "sriov-fec-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "sriov-fec-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "sriov-fec-operator.fullname" . }}-pre-delete-hook
  namespace: {{ .Release.Namespace }}
{{- end }}
