apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "sriov-fec-operator.fullname" . }}
  labels:
    {{- include "sriov-fec-operator.labels" . | nindent 4 }}
spec:
  {{- with .Values.subscription }}
  channel: {{ .channel | quote  }}
  name: sriov-fec
  source: {{ .source | quote  }}
  sourceNamespace: {{ .sourceNamespace | quote  }}
  installPlanApproval: {{ .installPlanApproval | quote  }}
  {{- end }}
